/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyHocSinh_Application;

import java.util.*;
//import java.awt.*;
import java.sql.*;
import javax.swing.*;
import MotaDoiTuong_entities.AccountGV;
import MotaDoiTuong_entities.AccountHS;
import LoginService.quanlydangnhap;
public class Form_Login extends javax.swing.JFrame {

    /**
     * Creates new form Form_Login
     */
    public Form_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLogin = new javax.swing.JButton();
        jtfPassword = new javax.swing.JTextField();
        lblogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jcbGhinho = new javax.swing.JCheckBox();
        anhnen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btLogin.setBackground(new java.awt.Color(255, 255, 0));
        btLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btLogin.setForeground(new java.awt.Color(153, 0, 0));
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 120, 45));

        jtfPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(jtfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 220, -1));

        lblogin.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblogin.setForeground(new java.awt.Color(153, 0, 0));
        lblogin.setText("LOGIN");
        getContentPane().add(lblogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setText("User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("PassWord");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jtfUser.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jtfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUserActionPerformed(evt);
            }
        });
        getContentPane().add(jtfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 220, 30));

        jcbGhinho.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jcbGhinho.setText("Ghi nhớ cho lần đăng nhập sau");
        jcbGhinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGhinhoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbGhinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        anhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Anh-Nen-Goc.png"))); // NOI18N
        getContentPane().add(anhnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        String userName = this.jtfUser.getText().trim();
        String password = this.jtfPassword.getText().trim();
        AccountHS accountHS = new AccountHS();
        AccountGV accountGV = new AccountGV();
        accountHS.setTenNguoiDung(userName);
        accountHS.setPassword(password);
        accountGV.setTenNguoiDung(userName);
        accountGV.setPassword(password);
     
        boolean loginFlag_HS = false;
        boolean loginFlag_GV= false;
        quanlydangnhap loginService = new quanlydangnhap();
         loginFlag_HS = loginService.Login_HS(accountHS);
         loginFlag_GV = loginService.Login_GV(accountGV);
        if ((loginFlag_HS = true) || (loginFlag_GV = true)) {
            dispose();
            Form_TrangChinh trangChinhFrame = new Form_TrangChinh();
            trangChinhFrame.setVisible(true);
            JOptionPane.showMessageDialog(this, "Ban da dang nhap thanh cong");
        } else {
            JOptionPane.showMessageDialog(this, "User hoac password sai!");
            jtfUser.setText("");
            jtfPassword.setText("");
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void jtfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUserActionPerformed

    private void jcbGhinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGhinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGhinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhnen;
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox jcbGhinho;
    private javax.swing.JTextField jtfPassword;
    private javax.swing.JTextField jtfUser;
    private javax.swing.JLabel lblogin;
    // End of variables declaration//GEN-END:variables
}
